name: Deploy a GitHub Pages

on:
  push:
    branches: ['main'] 

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
      
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.19.0
          
      - name: Instalar dependencias
        working-directory: ./portafolio-ronnie
        run: npm install
        
      - name: Construir el proyecto (Build)
        working-directory: ./portafolio-ronnie
        run: npm run build
        
      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v4
        
      - name: Subir artefactos
        uses: actions/upload-pages-artifact@v3
        with:
          path: './portafolio-ronnie/dist'
          
      - name: Desplegar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4